# Generated by Django 2.2 on 2021-01-03 17:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import managemiramar.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categorie',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telephone')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='prenom')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=managemiramar.models.rename_profil)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telephone')),
                ('message', models.TextField(max_length=3000)),
            ],
            options={
                'verbose_name': 'Contactez-Nous',
                'verbose_name_plural': 'Contactez-Nous',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le ')),
                ('name', models.CharField(blank=True, default='', max_length=125, verbose_name='nom')),
                ('photo', models.ImageField(upload_to=managemiramar.models.rename)),
                ('max_places', models.PositiveIntegerField(default=2, verbose_name='Maximum de personnes')),
                ('surface', models.PositiveIntegerField(default=25, verbose_name='Surface de la chambre')),
                ('price', models.FloatField(default=100, verbose_name='Prix')),
                ('description', ckeditor.fields.RichTextField()),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('promo', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorie', to='managemiramar.Category')),
            ],
            options={
                'verbose_name': 'Chambre',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrival_date_hour', models.DateTimeField(null=True, verbose_name="Temps d'arrivée")),
                ('departure_date_hour', models.DateTimeField(null=True, verbose_name='Temps de départ')),
                ('note', models.TextField(blank=True, default='', max_length=300, verbose_name='Message')),
                ('termined', models.BooleanField(default=False, verbose_name='Terminé')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='Occupants')),
                ('chambre', models.ManyToManyField(to='managemiramar.Room')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managemiramar.Client')),
            ],
            options={
                'verbose_name': 'Reservation',
            },
        ),
    ]
