# Generated by Django 2.2 on 2020-12-22 21:05

from django.db import migrations, models
import django.db.models.deletion
import managemiramar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=125)),
                ('photo', models.ImageField(upload_to=managemiramar.models.rename)),
                ('max_places', models.PositiveIntegerField(default=2)),
                ('surface', models.PositiveIntegerField(default=25)),
                ('price', models.FloatField(default=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('available', models.BooleanField(default=True)),
                ('promo', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='managemiramar.Category')),
            ],
            options={
                'verbose_name': 'Chambre',
                'ordering': ['-created_at'],
            },
        ),
    ]
