# Generated by Django 2.2 on 2020-12-24 15:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('managemiramar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telephone')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profil/<function rename at 0x0000026C41B6CE18>')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telephone')),
                ('message', models.CharField(max_length=3000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Categorie'},
        ),
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le '),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_places',
            field=models.PositiveIntegerField(default=2, verbose_name='Maximum de personnes'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, default='', max_length=125, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(default=100, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='room',
            name='surface',
            field=models.PositiveIntegerField(default=25, verbose_name='Surface de la chambre'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrival_date_hour', models.DateTimeField(verbose_name="Temps d'arrivée")),
                ('departure_date_hour', models.DateTimeField(verbose_name='Temps de départ')),
                ('note', models.CharField(max_length=300, verbose_name='Message')),
                ('termined', models.BooleanField(default=False, verbose_name='Terminé')),
                ('guests', models.PositiveIntegerField(default=1)),
                ('chambre', models.ManyToManyField(to='managemiramar.Room')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managemiramar.Client')),
            ],
        ),
    ]
