# Generated by Django 2.2 on 2021-01-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemiramar', '0002_booking_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prix'),
        ),
    ]
