# Generated by Django 2.2 on 2020-12-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemiramar', '0004_auto_20201226_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='chambre',
            field=models.ManyToManyField(null=True, to='managemiramar.Room'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profil/<function rename at 0x000002C5000458C8>'),
        ),
    ]
